# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'be_bi_application_frame/resources/application_frame.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 865)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_toolbar = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_toolbar.sizePolicy().hasHeightForWidth())
        self.top_toolbar.setSizePolicy(sizePolicy)
        self.top_toolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_toolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_toolbar.setObjectName("top_toolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_toolbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.future_timing_display = QtWidgets.QLabel(self.top_toolbar)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(True)
        self.future_timing_display.setFont(font)
        self.future_timing_display.setStyleSheet("padding: 10px;border:1px solid #aaaaaa;")
        self.future_timing_display.setObjectName("future_timing_display")
        self.horizontalLayout.addWidget(self.future_timing_display)
        spacerItem = QtWidgets.QSpacerItem(1137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.future_rbac_button = QtWidgets.QPushButton(self.top_toolbar)
        self.future_rbac_button.setStyleSheet("padding: 10px;margin:10px;")
        self.future_rbac_button.setFlat(False)
        self.future_rbac_button.setObjectName("future_rbac_button")
        self.horizontalLayout.addWidget(self.future_rbac_button)
        self.verticalLayout.addWidget(self.top_toolbar)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.central_widget_container = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget_container.sizePolicy().hasHeightForWidth())
        self.central_widget_container.setSizePolicy(sizePolicy)
        self.central_widget_container.setObjectName("central_widget_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_widget_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_tabs_widget = QtWidgets.QTabWidget(self.central_widget_container)
        self.main_tabs_widget.setObjectName("main_tabs_widget")
        self.first_tab = QtWidgets.QWidget()
        self.first_tab.setObjectName("first_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.first_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.first_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.scrolling_plot = ScrollingPlotWidget(self.first_tab)
        self.scrolling_plot.setStyleSheet("")
        self.scrolling_plot.setObjectName("scrolling_plot")
        self.verticalLayout_2.addWidget(self.scrolling_plot)
        self.label_2 = QtWidgets.QLabel(self.first_tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.main_tabs_widget.addTab(self.first_tab, "")
        self.second_tab = QtWidgets.QWidget()
        self.second_tab.setObjectName("second_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.second_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.second_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.cyclic_plot = CyclicPlotWidget(self.second_tab)
        self.cyclic_plot.setObjectName("cyclic_plot")
        self.verticalLayout_3.addWidget(self.cyclic_plot)
        self.main_tabs_widget.addTab(self.second_tab, "")
        self.horizontalLayout_2.addWidget(self.main_tabs_widget)
        self.bottom_logbox = CLogDisplay(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_logbox.sizePolicy().hasHeightForWidth())
        self.bottom_logbox.setSizePolicy(sizePolicy)
        self.bottom_logbox.setMaximumSize(QtCore.QSize(1500, 200))
        self.bottom_logbox.setProperty("logLevel", PyDMLogDisplay.INFO)
        self.bottom_logbox.setObjectName("bottom_logbox")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.main_tabs_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.future_timing_display.setText(_translate("Form", "Future location of the Timing Display"))
        self.future_rbac_button.setText(_translate("Form", "RBAC Token"))
        self.label.setText(_translate("Form", "Example plot: ScrollingPlot"))
        self.scrolling_plot.setToolTip(_translate("Form", "This plot is showing the value of TEST_DEVICE/Acquisition#sin over time"))
        self.scrolling_plot.setProperty("plotTitle", _translate("Form", "TEST_DEVICE/Acquisition#sin"))
        self.label_2.setText(_translate("Form", "To replace the content of this tab, remove them with ApplicationFrame.central_widget.removeTab(index) and use ApplicationFrame.central_widget.addTab(your_tab). To replace the entire tabbed container with your own GUI, do instead ApplicationFrame.setCentralWidget(your_gui_widget)."))
        self.main_tabs_widget.setTabText(self.main_tabs_widget.indexOf(self.first_tab), _translate("Form", "Tab 1"))
        self.label_5.setText(_translate("Form", "Example plot: CyclicPlot (or SlidingPlot)"))
        self.cyclic_plot.setToolTip(_translate("Form", "This plot is showing the value of TEST_DEVICE/Acquisition#sin over time"))
        self.cyclic_plot.setProperty("plotTitle", _translate("Form", "TEST_DEVICE/Acquisition#sin"))
        self.main_tabs_widget.setTabText(self.main_tabs_widget.indexOf(self.second_tab), _translate("Form", "Tab 2"))
        self.bottom_logbox.setProperty("logFormat", _translate("Form", "%(asctime)s %(message)s"))
from accwidgets.graph.widgets.plotwidget import CyclicPlotWidget, ScrollingPlotWidget
from comrad.widgets.tables import CLogDisplay
from pydm.widgets.logdisplay import PyDMLogDisplay
